from typing import List, Any


class Small_LLM_Model:
    def __init__(self) -> None: ...
    def get_logits_from_input_ids(
            self, input_ids: List[int]) -> List[float]: ...

    def get_path_to_vocab_file(self) -> str: ...
    def encode(self, text: str) -> Any: ...
    def decode(self, token_ids: List[int]) -> str: ...
